/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.webapk.Image', null, global);
goog.exportSymbol('proto.webapk.Image.Usage', null, global);
goog.exportSymbol('proto.webapk.ShareTarget', null, global);
goog.exportSymbol('proto.webapk.WebApk', null, global);
goog.exportSymbol('proto.webapk.WebApk.UpdateReason', null, global);
goog.exportSymbol('proto.webapk.WebApkResponse', null, global);
goog.exportSymbol('proto.webapk.WebAppManifest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webapk.WebApkResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.webapk.WebApkResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.webapk.WebApkResponse.displayName = 'proto.webapk.WebApkResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webapk.WebApkResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.webapk.WebApkResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webapk.WebApkResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.WebApkResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    packageName: jspb.Message.getField(msg, 1),
    version: jspb.Message.getField(msg, 2),
    token: jspb.Message.getField(msg, 6),
    relaxUpdates: jspb.Message.getField(msg, 8)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webapk.WebApkResponse}
 */
proto.webapk.WebApkResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webapk.WebApkResponse;
  return proto.webapk.WebApkResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webapk.WebApkResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webapk.WebApkResponse}
 */
proto.webapk.WebApkResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackageName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRelaxUpdates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webapk.WebApkResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webapk.WebApkResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webapk.WebApkResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.WebApkResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional string package_name = 1;
 * @return {string}
 */
proto.webapk.WebApkResponse.prototype.getPackageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.webapk.WebApkResponse.prototype.setPackageName = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.webapk.WebApkResponse.prototype.clearPackageName = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApkResponse.prototype.hasPackageName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.webapk.WebApkResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.webapk.WebApkResponse.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.webapk.WebApkResponse.prototype.clearVersion = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApkResponse.prototype.hasVersion = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string token = 6;
 * @return {string}
 */
proto.webapk.WebApkResponse.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.webapk.WebApkResponse.prototype.setToken = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.webapk.WebApkResponse.prototype.clearToken = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApkResponse.prototype.hasToken = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool relax_updates = 8;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.webapk.WebApkResponse.prototype.getRelaxUpdates = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 8, false));
};


/** @param {boolean} value */
proto.webapk.WebApkResponse.prototype.setRelaxUpdates = function(value) {
  jspb.Message.setField(this, 8, value);
};


proto.webapk.WebApkResponse.prototype.clearRelaxUpdates = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApkResponse.prototype.hasRelaxUpdates = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webapk.WebApk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.webapk.WebApk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.webapk.WebApk.displayName = 'proto.webapk.WebApk';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webapk.WebApk.prototype.toObject = function(opt_includeInstance) {
  return proto.webapk.WebApk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webapk.WebApk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.WebApk.toObject = function(includeInstance, msg) {
  var f, obj = {
    packageName: jspb.Message.getField(msg, 1),
    version: jspb.Message.getField(msg, 2),
    manifestUrl: jspb.Message.getField(msg, 3),
    requesterApplicationPackage: jspb.Message.getField(msg, 5),
    requesterApplicationVersion: jspb.Message.getField(msg, 6),
    manifest: (f = msg.getManifest()) && proto.webapk.WebAppManifest.toObject(includeInstance, f),
    androidAbi: jspb.Message.getField(msg, 8),
    staleManifest: jspb.Message.getField(msg, 9),
    updateReason: jspb.Message.getField(msg, 10)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webapk.WebApk}
 */
proto.webapk.WebApk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webapk.WebApk;
  return proto.webapk.WebApk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webapk.WebApk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webapk.WebApk}
 */
proto.webapk.WebApk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackageName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setManifestUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequesterApplicationPackage(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequesterApplicationVersion(value);
      break;
    case 7:
      var value = new proto.webapk.WebAppManifest;
      reader.readMessage(value,proto.webapk.WebAppManifest.deserializeBinaryFromReader);
      msg.setManifest(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setAndroidAbi(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStaleManifest(value);
      break;
    case 10:
      var value = /** @type {!proto.webapk.WebApk.UpdateReason} */ (reader.readEnum());
      msg.setUpdateReason(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webapk.WebApk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webapk.WebApk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webapk.WebApk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.WebApk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getManifest();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.webapk.WebAppManifest.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeBool(
      9,
      f
    );
  }
  f = /** @type {!proto.webapk.WebApk.UpdateReason} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeEnum(
      10,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.webapk.WebApk.UpdateReason = {
  NONE: 1,
  OLD_SHELL_APK: 2,
  PRIMARY_ICON_HASH_DIFFERS: 3,
  BADGE_ICON_HASH_DIFFERS: 4,
  SCOPE_DIFFERS: 5,
  START_URL_DIFFERS: 6,
  SHORT_NAME_DIFFERS: 7,
  NAME_DIFFERS: 8,
  BACKGROUND_COLOR_DIFFERS: 9,
  THEME_COLOR_DIFFERS: 10,
  ORIENTATION_DIFFERS: 11,
  DISPLAY_MODE_DIFFERS: 12
};

/**
 * optional string package_name = 1;
 * @return {string}
 */
proto.webapk.WebApk.prototype.getPackageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.webapk.WebApk.prototype.setPackageName = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.webapk.WebApk.prototype.clearPackageName = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasPackageName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.webapk.WebApk.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.webapk.WebApk.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.webapk.WebApk.prototype.clearVersion = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasVersion = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string manifest_url = 3;
 * @return {string}
 */
proto.webapk.WebApk.prototype.getManifestUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.webapk.WebApk.prototype.setManifestUrl = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.webapk.WebApk.prototype.clearManifestUrl = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasManifestUrl = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string requester_application_package = 5;
 * @return {string}
 */
proto.webapk.WebApk.prototype.getRequesterApplicationPackage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.webapk.WebApk.prototype.setRequesterApplicationPackage = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.webapk.WebApk.prototype.clearRequesterApplicationPackage = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasRequesterApplicationPackage = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string requester_application_version = 6;
 * @return {string}
 */
proto.webapk.WebApk.prototype.getRequesterApplicationVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.webapk.WebApk.prototype.setRequesterApplicationVersion = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.webapk.WebApk.prototype.clearRequesterApplicationVersion = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasRequesterApplicationVersion = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional WebAppManifest manifest = 7;
 * @return {?proto.webapk.WebAppManifest}
 */
proto.webapk.WebApk.prototype.getManifest = function() {
  return /** @type{?proto.webapk.WebAppManifest} */ (
    jspb.Message.getWrapperField(this, proto.webapk.WebAppManifest, 7));
};


/** @param {?proto.webapk.WebAppManifest|undefined} value */
proto.webapk.WebApk.prototype.setManifest = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.webapk.WebApk.prototype.clearManifest = function() {
  this.setManifest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasManifest = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string android_abi = 8;
 * @return {string}
 */
proto.webapk.WebApk.prototype.getAndroidAbi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.webapk.WebApk.prototype.setAndroidAbi = function(value) {
  jspb.Message.setField(this, 8, value);
};


proto.webapk.WebApk.prototype.clearAndroidAbi = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasAndroidAbi = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool stale_manifest = 9;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.webapk.WebApk.prototype.getStaleManifest = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 9, false));
};


/** @param {boolean} value */
proto.webapk.WebApk.prototype.setStaleManifest = function(value) {
  jspb.Message.setField(this, 9, value);
};


proto.webapk.WebApk.prototype.clearStaleManifest = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasStaleManifest = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional UpdateReason update_reason = 10;
 * @return {!proto.webapk.WebApk.UpdateReason}
 */
proto.webapk.WebApk.prototype.getUpdateReason = function() {
  return /** @type {!proto.webapk.WebApk.UpdateReason} */ (jspb.Message.getFieldWithDefault(this, 10, 1));
};


/** @param {!proto.webapk.WebApk.UpdateReason} value */
proto.webapk.WebApk.prototype.setUpdateReason = function(value) {
  jspb.Message.setField(this, 10, value);
};


proto.webapk.WebApk.prototype.clearUpdateReason = function() {
  jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebApk.prototype.hasUpdateReason = function() {
  return jspb.Message.getField(this, 10) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webapk.WebAppManifest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.webapk.WebAppManifest.repeatedFields_, null);
};
goog.inherits(proto.webapk.WebAppManifest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.webapk.WebAppManifest.displayName = 'proto.webapk.WebAppManifest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.webapk.WebAppManifest.repeatedFields_ = [5,6,17];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webapk.WebAppManifest.prototype.toObject = function(opt_includeInstance) {
  return proto.webapk.WebAppManifest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webapk.WebAppManifest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.WebAppManifest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getField(msg, 1),
    shortName: jspb.Message.getField(msg, 2),
    startUrl: jspb.Message.getField(msg, 4),
    scopesList: jspb.Message.getRepeatedField(msg, 5),
    iconsList: jspb.Message.toObjectList(msg.getIconsList(),
    proto.webapk.Image.toObject, includeInstance),
    orientation: jspb.Message.getField(msg, 9),
    displayMode: jspb.Message.getField(msg, 10),
    themeColor: jspb.Message.getField(msg, 11),
    backgroundColor: jspb.Message.getField(msg, 12),
    shareTargetsList: jspb.Message.toObjectList(msg.getShareTargetsList(),
    proto.webapk.ShareTarget.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webapk.WebAppManifest}
 */
proto.webapk.WebAppManifest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webapk.WebAppManifest;
  return proto.webapk.WebAppManifest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webapk.WebAppManifest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webapk.WebAppManifest}
 */
proto.webapk.WebAppManifest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setShortName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addScopes(value);
      break;
    case 6:
      var value = new proto.webapk.Image;
      reader.readMessage(value,proto.webapk.Image.deserializeBinaryFromReader);
      msg.addIcons(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrientation(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayMode(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setThemeColor(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setBackgroundColor(value);
      break;
    case 17:
      var value = new proto.webapk.ShareTarget;
      reader.readMessage(value,proto.webapk.ShareTarget.deserializeBinaryFromReader);
      msg.addShareTargets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webapk.WebAppManifest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webapk.WebAppManifest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webapk.WebAppManifest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.WebAppManifest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getScopesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getIconsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.webapk.Image.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeString(
      9,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeString(
      10,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeString(
      11,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getShareTargetsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      17,
      f,
      proto.webapk.ShareTarget.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.webapk.WebAppManifest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.webapk.WebAppManifest.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.webapk.WebAppManifest.prototype.clearName = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebAppManifest.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string short_name = 2;
 * @return {string}
 */
proto.webapk.WebAppManifest.prototype.getShortName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.webapk.WebAppManifest.prototype.setShortName = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.webapk.WebAppManifest.prototype.clearShortName = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebAppManifest.prototype.hasShortName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string start_url = 4;
 * @return {string}
 */
proto.webapk.WebAppManifest.prototype.getStartUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.webapk.WebAppManifest.prototype.setStartUrl = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.webapk.WebAppManifest.prototype.clearStartUrl = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebAppManifest.prototype.hasStartUrl = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string scopes = 5;
 * @return {!Array<string>}
 */
proto.webapk.WebAppManifest.prototype.getScopesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.webapk.WebAppManifest.prototype.setScopesList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.webapk.WebAppManifest.prototype.addScopes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.webapk.WebAppManifest.prototype.clearScopesList = function() {
  this.setScopesList([]);
};


/**
 * repeated Image icons = 6;
 * @return {!Array<!proto.webapk.Image>}
 */
proto.webapk.WebAppManifest.prototype.getIconsList = function() {
  return /** @type{!Array<!proto.webapk.Image>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.webapk.Image, 6));
};


/** @param {!Array<!proto.webapk.Image>} value */
proto.webapk.WebAppManifest.prototype.setIconsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.webapk.Image=} opt_value
 * @param {number=} opt_index
 * @return {!proto.webapk.Image}
 */
proto.webapk.WebAppManifest.prototype.addIcons = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.webapk.Image, opt_index);
};


proto.webapk.WebAppManifest.prototype.clearIconsList = function() {
  this.setIconsList([]);
};


/**
 * optional string orientation = 9;
 * @return {string}
 */
proto.webapk.WebAppManifest.prototype.getOrientation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.webapk.WebAppManifest.prototype.setOrientation = function(value) {
  jspb.Message.setField(this, 9, value);
};


proto.webapk.WebAppManifest.prototype.clearOrientation = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebAppManifest.prototype.hasOrientation = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string display_mode = 10;
 * @return {string}
 */
proto.webapk.WebAppManifest.prototype.getDisplayMode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.webapk.WebAppManifest.prototype.setDisplayMode = function(value) {
  jspb.Message.setField(this, 10, value);
};


proto.webapk.WebAppManifest.prototype.clearDisplayMode = function() {
  jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebAppManifest.prototype.hasDisplayMode = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string theme_color = 11;
 * @return {string}
 */
proto.webapk.WebAppManifest.prototype.getThemeColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.webapk.WebAppManifest.prototype.setThemeColor = function(value) {
  jspb.Message.setField(this, 11, value);
};


proto.webapk.WebAppManifest.prototype.clearThemeColor = function() {
  jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebAppManifest.prototype.hasThemeColor = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string background_color = 12;
 * @return {string}
 */
proto.webapk.WebAppManifest.prototype.getBackgroundColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.webapk.WebAppManifest.prototype.setBackgroundColor = function(value) {
  jspb.Message.setField(this, 12, value);
};


proto.webapk.WebAppManifest.prototype.clearBackgroundColor = function() {
  jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.WebAppManifest.prototype.hasBackgroundColor = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * repeated ShareTarget share_targets = 17;
 * @return {!Array<!proto.webapk.ShareTarget>}
 */
proto.webapk.WebAppManifest.prototype.getShareTargetsList = function() {
  return /** @type{!Array<!proto.webapk.ShareTarget>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.webapk.ShareTarget, 17));
};


/** @param {!Array<!proto.webapk.ShareTarget>} value */
proto.webapk.WebAppManifest.prototype.setShareTargetsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 17, value);
};


/**
 * @param {!proto.webapk.ShareTarget=} opt_value
 * @param {number=} opt_index
 * @return {!proto.webapk.ShareTarget}
 */
proto.webapk.WebAppManifest.prototype.addShareTargets = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 17, opt_value, proto.webapk.ShareTarget, opt_index);
};


proto.webapk.WebAppManifest.prototype.clearShareTargetsList = function() {
  this.setShareTargetsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webapk.Image = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.webapk.Image.repeatedFields_, null);
};
goog.inherits(proto.webapk.Image, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.webapk.Image.displayName = 'proto.webapk.Image';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.webapk.Image.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webapk.Image.prototype.toObject = function(opt_includeInstance) {
  return proto.webapk.Image.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webapk.Image} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.Image.toObject = function(includeInstance, msg) {
  var f, obj = {
    src: jspb.Message.getField(msg, 1),
    hash: jspb.Message.getField(msg, 5),
    imageData: msg.getImageData_asB64(),
    usagesList: jspb.Message.getRepeatedField(msg, 8)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webapk.Image}
 */
proto.webapk.Image.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webapk.Image;
  return proto.webapk.Image.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webapk.Image} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webapk.Image}
 */
proto.webapk.Image.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSrc(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImageData(value);
      break;
    case 8:
      var value = /** @type {!proto.webapk.Image.Usage} */ (reader.readEnum());
      msg.addUsages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webapk.Image.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webapk.Image.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webapk.Image} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.Image.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBytes(
      6,
      f
    );
  }
  f = message.getUsagesList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.webapk.Image.Usage = {
  PRIMARY_ICON: 1,
  BADGE_ICON: 2
};

/**
 * optional string src = 1;
 * @return {string}
 */
proto.webapk.Image.prototype.getSrc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.webapk.Image.prototype.setSrc = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.webapk.Image.prototype.clearSrc = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.Image.prototype.hasSrc = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string hash = 5;
 * @return {string}
 */
proto.webapk.Image.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.webapk.Image.prototype.setHash = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.webapk.Image.prototype.clearHash = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.Image.prototype.hasHash = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bytes image_data = 6;
 * @return {!(string|Uint8Array)}
 */
proto.webapk.Image.prototype.getImageData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes image_data = 6;
 * This is a type-conversion wrapper around `getImageData()`
 * @return {string}
 */
proto.webapk.Image.prototype.getImageData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImageData()));
};


/**
 * optional bytes image_data = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImageData()`
 * @return {!Uint8Array}
 */
proto.webapk.Image.prototype.getImageData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImageData()));
};


/** @param {!(string|Uint8Array)} value */
proto.webapk.Image.prototype.setImageData = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.webapk.Image.prototype.clearImageData = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.Image.prototype.hasImageData = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated Usage usages = 8;
 * @return {!Array<!proto.webapk.Image.Usage>}
 */
proto.webapk.Image.prototype.getUsagesList = function() {
  return /** @type {!Array<!proto.webapk.Image.Usage>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<!proto.webapk.Image.Usage>} value */
proto.webapk.Image.prototype.setUsagesList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {!proto.webapk.Image.Usage} value
 * @param {number=} opt_index
 */
proto.webapk.Image.prototype.addUsages = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


proto.webapk.Image.prototype.clearUsagesList = function() {
  this.setUsagesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webapk.ShareTarget = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.webapk.ShareTarget, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.webapk.ShareTarget.displayName = 'proto.webapk.ShareTarget';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webapk.ShareTarget.prototype.toObject = function(opt_includeInstance) {
  return proto.webapk.ShareTarget.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webapk.ShareTarget} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.ShareTarget.toObject = function(includeInstance, msg) {
  var f, obj = {
    urlTemplate: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webapk.ShareTarget}
 */
proto.webapk.ShareTarget.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webapk.ShareTarget;
  return proto.webapk.ShareTarget.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webapk.ShareTarget} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webapk.ShareTarget}
 */
proto.webapk.ShareTarget.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrlTemplate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webapk.ShareTarget.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webapk.ShareTarget.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webapk.ShareTarget} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webapk.ShareTarget.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string url_template = 1;
 * @return {string}
 */
proto.webapk.ShareTarget.prototype.getUrlTemplate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.webapk.ShareTarget.prototype.setUrlTemplate = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.webapk.ShareTarget.prototype.clearUrlTemplate = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.webapk.ShareTarget.prototype.hasUrlTemplate = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.webapk);
